// Code generated by mockery. DO NOT EDIT.

package quotemocks

import (
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// MarketPriceProvider is an autogenerated mock type for the MarketPriceProvider type
type MarketPriceProvider struct {
	mock.Mock
}

type MarketPriceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MarketPriceProvider) EXPECT() *MarketPriceProvider_Expecter {
	return &MarketPriceProvider_Expecter{mock: &_m.Mock}
}

// CurrentPrice provides a mock function with no fields
func (_m *MarketPriceProvider) CurrentPrice() (decimal.Decimal, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrentPrice")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func() (decimal.Decimal, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() decimal.Decimal); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarketPriceProvider_CurrentPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentPrice'
type MarketPriceProvider_CurrentPrice_Call struct {
	*mock.Call
}

// CurrentPrice is a helper method to define mock.On call
func (_e *MarketPriceProvider_Expecter) CurrentPrice() *MarketPriceProvider_CurrentPrice_Call {
	return &MarketPriceProvider_CurrentPrice_Call{Call: _e.mock.On("CurrentPrice")}
}

func (_c *MarketPriceProvider_CurrentPrice_Call) Run(run func()) *MarketPriceProvider_CurrentPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarketPriceProvider_CurrentPrice_Call) Return(_a0 decimal.Decimal, _a1 error) *MarketPriceProvider_CurrentPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MarketPriceProvider_CurrentPrice_Call) RunAndReturn(run func() (decimal.Decimal, error)) *MarketPriceProvider_CurrentPrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarketPriceProvider creates a new instance of MarketPriceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarketPriceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarketPriceProvider {
	mock := &MarketPriceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
