with-expecter: true
quiet: false
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
filename: "{{.InterfaceName}}.go"
dir: "domain/mocks/{{.PackageName}}"
outpkg: "{{.PackageName}}mocks"
mockname: "{{.InterfaceName}}"
packages:
  github.com/Touutae-labs/friendly-system/domain/module/balance:
    interfaces:
      AccountRepository:
  github.com/Touutae-labs/friendly-system/domain/module/quote:
    interfaces:
      MarketPriceProvider:
  github.com/Touutae-labs/friendly-system/domain/module/limit:
    interfaces:
      DailyLedger:
