// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Touutae-labs/friendly-system/internal/configurations"
	controller "github.com/Touutae-labs/friendly-system/internal/controllers"
	"github.com/Touutae-labs/friendly-system/internal/modules/balance"
	"github.com/Touutae-labs/friendly-system/internal/modules/limit"
	"github.com/Touutae-labs/friendly-system/internal/modules/orderval"
	"github.com/Touutae-labs/friendly-system/internal/modules/quote"
	"github.com/Touutae-labs/friendly-system/internal/server"
	"github.com/Touutae-labs/friendly-system/internal/service/processor"
	validatorsvc "github.com/Touutae-labs/friendly-system/internal/service/validator"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initialize(cfg configurations.Config, title server.ServerTitle, version server.ServerVersion) (*Application, func(), error) {
	serverConfig := cfg.Server
	serverServerConfig := provideServerConfig(serverConfig, title, version)
	healthController := controller.NewHealthController()

	ordervalConfig, err := provideOrderValConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	ordervalValidator, err := orderval.New(ordervalConfig)
	if err != nil {
		return nil, nil, err
	}

	quoteConfig, err := provideQuoteConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	marketPriceProvider := provideMarket()
	quoteValidator, err := quote.New(quoteConfig, marketPriceProvider)
	if err != nil {
		return nil, nil, err
	}

	databaseConfig := cfg.Database
	db, cleanup, err := provideDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}

	accountRepository := provideAccountsGorm(db)
	balanceModule, err := balance.New(accountRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	limitConfig, err := provideLimitConfig(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dailyLedger := provideLedgerGorm(db)
	limitModule, err := limit.New(limitConfig, dailyLedger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	validatorService := validatorsvc.New(ordervalValidator, quoteValidator, balanceModule, limitModule)
	orderRepository := provideOrdersGorm(db)
	processorService := processor.New(db, validatorService, balanceModule, limitModule, orderRepository, limitConfig)
	orderController := controller.NewOrderController(validatorService, processorService)
	controllers := controller.NewControllers(healthController, orderController)
	serverServer := provideServerAndRegisterHandlers(serverServerConfig, controllers)
	application := &Application{
		Server: serverServer,
		DB:     db,
	}
	return application, func() {
		cleanup()
	}, nil
}

// wire.go:

// Application holds all top-level components of the application.
type Application struct {
	Server *server.Server
	DB     *gorm.DB
}

var serverSet = wire.NewSet(wire.FieldsOf(new(configurations.Config), "Server"), provideServerConfig,
	provideServerAndRegisterHandlers,
)

var controllersSet = wire.NewSet(controller.NewControllers, controller.NewHealthController, controller.NewOrderController)

var servicesSet = wire.NewSet(validatorsvc.New, processor.New)

var modulesSet = wire.NewSet(provideOrderValConfig, orderval.New, provideQuoteConfig, quote.New, balance.New, provideLimitConfig, limit.New)

var repositoriesSet = wire.NewSet(
	provideAccountsGorm,
	provideLedgerGorm,
	provideOrdersGorm,
)

var dbSet = wire.NewSet(wire.FieldsOf(new(configurations.Config), "Database"), provideDB)

// Initialize is the main entrypoint for dependency injection.
func Initialize(cfg configurations.Config, title server.ServerTitle, version server.ServerVersion) (*server.Server, func(), error) {
	app, cleanup, err := initialize(cfg, title, version)
	if err != nil {
		return nil, nil, err
	}
	return app.Server, cleanup, nil
}

// InitializeApp returns the full Application including DB access (useful for seeding in tests).
func InitializeApp(cfg configurations.Config, title server.ServerTitle, version server.ServerVersion) (*Application, func(), error) {
	return initialize(cfg, title, version)
}
