// Code generated by mockery. DO NOT EDIT.

package balancemocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function with given fields: ctx, customerID
func (_m *AccountRepository) Balance(ctx context.Context, customerID string) (decimal.Decimal, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (decimal.Decimal, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) decimal.Decimal); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type AccountRepository_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *AccountRepository_Expecter) Balance(ctx interface{}, customerID interface{}) *AccountRepository_Balance_Call {
	return &AccountRepository_Balance_Call{Call: _e.mock.On("Balance", ctx, customerID)}
}

func (_c *AccountRepository_Balance_Call) Run(run func(ctx context.Context, customerID string)) *AccountRepository_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountRepository_Balance_Call) Return(_a0 decimal.Decimal, _a1 error) *AccountRepository_Balance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_Balance_Call) RunAndReturn(run func(context.Context, string) (decimal.Decimal, error)) *AccountRepository_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// LockAndGetBalance provides a mock function with given fields: ctx, tx, customerID
func (_m *AccountRepository) LockAndGetBalance(ctx context.Context, tx *gorm.DB, customerID string) (decimal.Decimal, error) {
	ret := _m.Called(ctx, tx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for LockAndGetBalance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (decimal.Decimal, error)); ok {
		return rf(ctx, tx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) decimal.Decimal); ok {
		r0 = rf(ctx, tx, customerID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_LockAndGetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockAndGetBalance'
type AccountRepository_LockAndGetBalance_Call struct {
	*mock.Call
}

// LockAndGetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - customerID string
func (_e *AccountRepository_Expecter) LockAndGetBalance(ctx interface{}, tx interface{}, customerID interface{}) *AccountRepository_LockAndGetBalance_Call {
	return &AccountRepository_LockAndGetBalance_Call{Call: _e.mock.On("LockAndGetBalance", ctx, tx, customerID)}
}

func (_c *AccountRepository_LockAndGetBalance_Call) Run(run func(ctx context.Context, tx *gorm.DB, customerID string)) *AccountRepository_LockAndGetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(string))
	})
	return _c
}

func (_c *AccountRepository_LockAndGetBalance_Call) Return(_a0 decimal.Decimal, _a1 error) *AccountRepository_LockAndGetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_LockAndGetBalance_Call) RunAndReturn(run func(context.Context, *gorm.DB, string) (decimal.Decimal, error)) *AccountRepository_LockAndGetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function with given fields: ctx, tx, customerID, newBalance
func (_m *AccountRepository) UpdateBalance(ctx context.Context, tx *gorm.DB, customerID string, newBalance decimal.Decimal) error {
	ret := _m.Called(ctx, tx, customerID, newBalance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, decimal.Decimal) error); ok {
		r0 = rf(ctx, tx, customerID, newBalance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountRepository_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type AccountRepository_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - customerID string
//   - newBalance decimal.Decimal
func (_e *AccountRepository_Expecter) UpdateBalance(ctx interface{}, tx interface{}, customerID interface{}, newBalance interface{}) *AccountRepository_UpdateBalance_Call {
	return &AccountRepository_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, tx, customerID, newBalance)}
}

func (_c *AccountRepository_UpdateBalance_Call) Run(run func(ctx context.Context, tx *gorm.DB, customerID string, newBalance decimal.Decimal)) *AccountRepository_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gorm.DB), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *AccountRepository_UpdateBalance_Call) Return(_a0 error) *AccountRepository_UpdateBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountRepository_UpdateBalance_Call) RunAndReturn(run func(context.Context, *gorm.DB, string, decimal.Decimal) error) *AccountRepository_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
