// Code generated by mockery. DO NOT EDIT.

package balancemocks

import (
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function with given fields: customerID
func (_m *AccountRepository) Balance(customerID string) (decimal.Decimal, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (decimal.Decimal, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(string) decimal.Decimal); ok {
		r0 = rf(customerID)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type AccountRepository_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - customerID string
func (_e *AccountRepository_Expecter) Balance(customerID interface{}) *AccountRepository_Balance_Call {
	return &AccountRepository_Balance_Call{Call: _e.mock.On("Balance", customerID)}
}

func (_c *AccountRepository_Balance_Call) Run(run func(customerID string)) *AccountRepository_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AccountRepository_Balance_Call) Return(_a0 decimal.Decimal, _a1 error) *AccountRepository_Balance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_Balance_Call) RunAndReturn(run func(string) (decimal.Decimal, error)) *AccountRepository_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
