// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/pantakan/intergold-validator/domain/module/balance"
	"github.com/pantakan/intergold-validator/domain/module/limit"
	"github.com/pantakan/intergold-validator/domain/module/orderval"
	"github.com/pantakan/intergold-validator/domain/module/quote"
	"github.com/pantakan/intergold-validator/domain/service/validator"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitValidatorService() (*validatorsvc.Service, error) {
	config := orderval.DefaultConfig()
	validator, err := orderval.New(config)
	if err != nil {
		return nil, err
	}
	quoteConfig := quote.DefaultConfig()
	marketPriceProvider := provideMarket()
	quoteValidator, err := quote.New(quoteConfig, marketPriceProvider)
	if err != nil {
		return nil, err
	}
	accountRepository := provideAccounts()
	balanceValidator, err := balance.New(accountRepository)
	if err != nil {
		return nil, err
	}
	limitConfig := limit.DefaultConfig()
	dailyLedger := provideLedger()
	limitValidator, err := limit.New(limitConfig, dailyLedger)
	if err != nil {
		return nil, err
	}
	service := validatorsvc.New(validator, quoteValidator, balanceValidator, limitValidator)
	return service, nil
}

func InitValidatorServiceGorm(db *gorm.DB) (*validatorsvc.Service, error) {
	config := orderval.DefaultConfig()
	validator, err := orderval.New(config)
	if err != nil {
		return nil, err
	}
	quoteConfig := quote.DefaultConfig()
	marketPriceProvider := provideMarket()
	quoteValidator, err := quote.New(quoteConfig, marketPriceProvider)
	if err != nil {
		return nil, err
	}
	accountRepository := provideAccountsGorm(db)
	balanceValidator, err := balance.New(accountRepository)
	if err != nil {
		return nil, err
	}
	limitConfig := limit.DefaultConfig()
	dailyLedger := provideLedgerGorm(db)
	limitValidator, err := limit.New(limitConfig, dailyLedger)
	if err != nil {
		return nil, err
	}
	service := validatorsvc.New(validator, quoteValidator, balanceValidator, limitValidator)
	return service, nil
}

// wire.go:

var moduleSet = wire.NewSet(orderval.DefaultConfig, orderval.New, quote.DefaultConfig, quote.New, balance.New, limit.DefaultConfig, limit.New, validatorsvc.New)
