// Code generated by mockery. DO NOT EDIT.

package limitmocks

import (
	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DailyLedger is an autogenerated mock type for the DailyLedger type
type DailyLedger struct {
	mock.Mock
}

type DailyLedger_Expecter struct {
	mock *mock.Mock
}

func (_m *DailyLedger) EXPECT() *DailyLedger_Expecter {
	return &DailyLedger_Expecter{mock: &_m.Mock}
}

// TradedToday provides a mock function with given fields: customerID, now
func (_m *DailyLedger) TradedToday(customerID string, now time.Time) (decimal.Decimal, error) {
	ret := _m.Called(customerID, now)

	if len(ret) == 0 {
		panic("no return value specified for TradedToday")
	}

	var r0 decimal.Decimal
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) (decimal.Decimal, error)); ok {
		return rf(customerID, now)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) decimal.Decimal); ok {
		r0 = rf(customerID, now)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(customerID, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DailyLedger_TradedToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TradedToday'
type DailyLedger_TradedToday_Call struct {
	*mock.Call
}

// TradedToday is a helper method to define mock.On call
//   - customerID string
//   - now time.Time
func (_e *DailyLedger_Expecter) TradedToday(customerID interface{}, now interface{}) *DailyLedger_TradedToday_Call {
	return &DailyLedger_TradedToday_Call{Call: _e.mock.On("TradedToday", customerID, now)}
}

func (_c *DailyLedger_TradedToday_Call) Run(run func(customerID string, now time.Time)) *DailyLedger_TradedToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *DailyLedger_TradedToday_Call) Return(_a0 decimal.Decimal, _a1 error) *DailyLedger_TradedToday_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DailyLedger_TradedToday_Call) RunAndReturn(run func(string, time.Time) (decimal.Decimal, error)) *DailyLedger_TradedToday_Call {
	_c.Call.Return(run)
	return _c
}

// NewDailyLedger creates a new instance of DailyLedger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDailyLedger(t interface {
	mock.TestingT
	Cleanup(func())
}) *DailyLedger {
	mock := &DailyLedger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
